<?php

require_once(UTILS_PATH . "DataRepositoryUtil.php");
require_once(MODEL_PATH . "Contact.php");

class ContactDataRepository implements DataRepository
{
    private mysqli $connection;
    private UserDataRepository $userRepo;

    public function __construct(mysqli $connection)
    {
        $this->connection = $connection;
        $this->userRepo = new UserDataRepository($connection);
    }

    public function searchById($id)
    {
        $query = "SELECT * FROM Contact WHERE contact_id = ?";
        $paramTypes = "i";
        $stmt = prepareAndExecuteQuery($this->connection, $query, $paramTypes, $id);

        $mysqli_result = $stmt->get_result();
        if ($mysqli_result->num_rows <= 0) {
            throw new mysqli_sql_exception("User with the given id is not found");
        }

        $result = $mysqli_result->fetch_assoc();
        $stmt->close();
        return $this->mapRowToContactObject($result);
    }

    public function getLists(): ?array
    {
        $query = "SELECT * FROM Contact";
        $stmt = $this->connection->prepare($query);

        if (!$stmt->execute()) {
            throw new mysqli_sql_exception("Error executing the given sql statement.");
        }

        $mysqli_result = $stmt->get_result();
        $userList = [];
        while ($row = $mysqli_result->fetch_assoc()) {
            $user = $this->mapRowToContactObject($row);
            $userList[] = $user;
        }
        $stmt->close();
        return $userList;
    }

    public function update($existingData, $newData): int|string
    {
        $query = "UPDATE Contact SET  message = ?, status = ?  WHERE contact_id = ?";
        $paramsType = 'ssi';
        $stmt = prepareAndExecuteQuery($this->connection, $query, $paramsType, $newData->getMessage(), $newData->getStatus(), $existingData->getContactId());

        $affectedRow = $stmt->affected_rows;
        $stmt->close();
        return $affectedRow;
    }

    public function insert($data): int|string
    {
        $query = "INSERT INTO Contact(message,user_id,status) VALUES (?, ?,?)";
        $paramTypes = "sis";
        $stmt = prepareAndExecuteQuery($this->connection, $query, $paramTypes, $data->getMessage(), $data->getUser()->getUserId(),$data->getStatus());

        $affectedRow = $stmt->affected_rows;
        $autoGeneratedID = $this->connection->insert_id;
        $stmt->close();
        return $autoGeneratedID;
    }

    public function remove($id): int|string
    {
        $query = "DELETE FROM Contact WHERE contact_id = ?";
        $paramTypes = "i";
        $stmt = prepareAndExecuteQuery($this->connection, $query, $paramTypes, $id);
        $affectedRow = $stmt->affected_rows;
        $stmt->close();
        return $affectedRow;
    }

    private function mapRowToContactObject($row): Contact
    {
        $dateTime = new DateTime($row["contact_date"]);
        $user = $this->userRepo->searchById($row["user_id"]);
        $contact = new Contact($row['message'], $row['status'], $dateTime, $user);
        $contact->setContactId($row['contact_id']);
        return $contact;
    }
}
